ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MT,MDL_MW,MDL_MEV,MDL_MPE1,MDL_MPE2,MDL_MZ
     $ ,MDL_MTA,MDL_MB,MDL_MUV,MDL_MH

      COMMON/MASSES/ MDL_MT,MDL_MW,MDL_MEV,MDL_MPE1,MDL_MPE2,MDL_MZ
     $ ,MDL_MTA,MDL_MB,MDL_MUV,MDL_MH


      DOUBLE PRECISION MDL_WEV,MDL_WW,MDL_WT,MDL_WZ,MDL_WPE1,MDL_WUV
     $ ,MDL_WPE2,MDL_WH

      COMMON/WIDTHS/ MDL_WEV,MDL_WW,MDL_WT,MDL_WZ,MDL_WPE1,MDL_WUV
     $ ,MDL_WPE2,MDL_WH


      DOUBLE COMPLEX GC_10, GC_11

      COMMON/COUPLINGS/ GC_10, GC_11

