ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of Tutorial_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_10 = ', GC_10
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_71 = ', GC_71
      WRITE(*,2) 'GC_72 = ', GC_72
