ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of MSSMD_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_15229 = ', GC_15229
      WRITE(*,2) 'GC_15483 = ', GC_15483
      WRITE(*,2) 'GC_10 = ', GC_10
      WRITE(*,2) 'GC_11 = ', GC_11
