ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'mdl_ymb = ', MDL_YMB
      WRITE(*,*) 'mdl_ymt = ', MDL_YMT
      WRITE(*,*) 'mdl_ymtau = ', MDL_YMTAU
      WRITE(*,*) 'mdl_MM1 = ', MDL_MM1
      WRITE(*,*) 'mdl_MM2 = ', MDL_MM2
      WRITE(*,*) 'mdl_MM12 = ', MDL_MM12
      WRITE(*,*) 'mdl_lam11 = ', MDL_LAM11
      WRITE(*,*) 'mdl_lam12 = ', MDL_LAM12
      WRITE(*,*) 'mdl_lam13 = ', MDL_LAM13
      WRITE(*,*) 'mdl_lam21 = ', MDL_LAM21
      WRITE(*,*) 'mdl_lam22 = ', MDL_LAM22
      WRITE(*,*) 'mdl_lam23 = ', MDL_LAM23
      WRITE(*,*) 'mdl_lam1p1 = ', MDL_LAM1P1
      WRITE(*,*) 'mdl_lam1p2 = ', MDL_LAM1P2
      WRITE(*,*) 'mdl_lam1p3 = ', MDL_LAM1P3
      WRITE(*,*) 'mdl_lam2p1 = ', MDL_LAM2P1
      WRITE(*,*) 'mdl_lam2p2 = ', MDL_LAM2P2
      WRITE(*,*) 'mdl_lam2p3 = ', MDL_LAM2P3
      WRITE(*,*) 'mdl_MZ = ', MDL_MZ
      WRITE(*,*) 'mdl_MTA = ', MDL_MTA
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_MB = ', MDL_MB
      WRITE(*,*) 'mdl_MH = ', MDL_MH
      WRITE(*,*) 'mdl_Muv = ', MDL_MUV
      WRITE(*,*) 'mdl_Mev = ', MDL_MEV
      WRITE(*,*) 'mdl_WZ = ', MDL_WZ
      WRITE(*,*) 'mdl_WW = ', MDL_WW
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_WH = ', MDL_WH
      WRITE(*,*) 'mdl_Wpe1 = ', MDL_WPE1
      WRITE(*,*) 'mdl_Wpe2 = ', MDL_WPE2
      WRITE(*,*) 'mdl_Wuv = ', MDL_WUV
      WRITE(*,*) 'mdl_Wev = ', MDL_WEV
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_MM1__exp__2 = ', MDL_MM1__EXP__2
      WRITE(*,*) 'mdl_MM2__exp__2 = ', MDL_MM2__EXP__2
      WRITE(*,*) 'mdl_MM1__exp__4 = ', MDL_MM1__EXP__4
      WRITE(*,*) 'mdl_MM12__exp__4 = ', MDL_MM12__EXP__4
      WRITE(*,*) 'mdl_MM2__exp__4 = ', MDL_MM2__EXP__4
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_MPe1 = ', MDL_MPE1
      WRITE(*,*) 'mdl_MPe2 = ', MDL_MPE2
      WRITE(*,*) 'mdl_MM12__exp__2 = ', MDL_MM12__EXP__2
      WRITE(*,*) 'mdl_th = ', MDL_TH
      WRITE(*,*) 'mdl_MZ__exp__2 = ', MDL_MZ__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__4 = ', MDL_MZ__EXP__4
      WRITE(*,*) 'mdl_MH__exp__2 = ', MDL_MH__EXP__2
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_cos__th = ', MDL_COS__TH
      WRITE(*,*) 'mdl_sin__th = ', MDL_SIN__TH
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_MW = ', MDL_MW
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_MW__exp__2 = ', MDL_MW__EXP__2
      WRITE(*,*) 'mdl_sw2 = ', MDL_SW2
      WRITE(*,*) 'mdl_cw = ', MDL_CW
      WRITE(*,*) 'mdl_sqrt__sw2 = ', MDL_SQRT__SW2
      WRITE(*,*) 'mdl_sw = ', MDL_SW
      WRITE(*,*) 'mdl_g1 = ', MDL_G1
      WRITE(*,*) 'mdl_gw = ', MDL_GW
      WRITE(*,*) 'mdl_vev = ', MDL_VEV
      WRITE(*,*) 'mdl_vev__exp__2 = ', MDL_VEV__EXP__2
      WRITE(*,*) 'mdl_lam = ', MDL_LAM
      WRITE(*,*) 'mdl_yb = ', MDL_YB
      WRITE(*,*) 'mdl_yt = ', MDL_YT
      WRITE(*,*) 'mdl_ytau = ', MDL_YTAU
      WRITE(*,*) 'mdl_muH = ', MDL_MUH
      WRITE(*,*) 'mdl_I1b33 = ', MDL_I1B33
      WRITE(*,*) 'mdl_I2b33 = ', MDL_I2B33
      WRITE(*,*) 'mdl_I3b33 = ', MDL_I3B33
      WRITE(*,*) 'mdl_I4b33 = ', MDL_I4B33
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*) 'mdl_sw__exp__2 = ', MDL_SW__EXP__2
      WRITE(*,*) 'mdl_cw__exp__2 = ', MDL_CW__EXP__2
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
